#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
#obj-$(CONFIG_LGE_BROADCAST_ONESEG)		+= broadcast_dmb_drv_if.o
#obj-$(CONFIG_LGE_BROADCAST_ONESEG_FC8150)		+= fc8150/
obj-$(CONFIG_FCI_FC8150_SPI) += fc8150/
