#ifndef _SMI_NAME_H_
#define _SMI_NAME_H_

enum SMI_DEST {SMI_DEST_ALL=0, SMI_DEST_EMI=1, SMI_DEST_INTERNAL=3, SMI_DEST_NONE=99};
enum SMI_RW {SMI_RW_ALL=0, SMI_READ_ONLY=1, SMI_WRITE_ONLY=2, SMI_RW_RESPECTIVE, SMI_RW_NONE=99};
enum SMI_BUS {SMI_BUS_GMC=0, SMI_BUS_AXI=1, SMI_BUS_NONE=99};
/*
typedef struct {
	unsigned long u4Master;   //SMI master 0~3
	unsigned long u4PortNo;
	unsigned long bBusType : 1;//0 for GMC, 1 for AXI
	unsigned long bDestType : 2;//0 for EMI+internal mem, 1 for EMI, 3 for internal mem
	unsigned long bRWType : 2;//0 for R+W, 1 for read, 2 for write
}SMIBMCfg;
*/

struct smi_desc {
	unsigned long port;
	char name[40];
	enum SMI_DEST desttype;
	enum SMI_RW rwtype;
	enum SMI_BUS bustype;
};

/* mt6577 */
struct smi_desc larb0_desc[] = {
	{ 0,	"DEFECT",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 1,	"JPG_ENC",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 2,	"ROT_DMA0_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 3,	"ROT_DMA1_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 4,	"TV_ROT_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 5,	"CAM",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 6,	"FD0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 7,	"FD2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 8,	"JPG_DEC0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 9,	"R_DMA0_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 10,	"R_DMA0_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 11,	"R_DMA0_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 12,	"FD1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 13,	"PCA",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 14,	"JPGDMA_R",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 15,	"JPGDMA_W",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 16,	"ROT_DMA0_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 17,	"ROT_DMA0_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 18,	"ROT_DMA1_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 19,	"ROT_DMA1_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 20,	"TV_ROT_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 21,	"TV_ROT_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 22,	"R_DMA0_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 23,	"JPG_DEC1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC},
	{ 24,	"TV_ROT_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 25,	"ROT_DMA0_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 26,	"ROT_DMA1_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
};
struct smi_desc larb1_desc[] = {
	{ 0, "OVL_MSK",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 1, "OVL_DCP",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 2, "DPI",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 3, "ROT_DMA2_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 4, "ROT_DMA3_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 5, "ROT_DMA4_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 6, "TVC",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 7, "LCD_R",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 8, "LCD_W",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 9, "R_DMA1_OUT0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 10, "R_DMA1_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 11, "R_DMA1_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 12, "SPI",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 13, "DUMMY",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 14, "DPI_HWC",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 15, "VRZ",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 16, "ROT_DMA2_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 17, "ROT_DMA2_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 18, "ROT_DMA3_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 19, "ROT_DMA3_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 20, "ROT_DMA4_OUT1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 21, "ROT_DMA4_OUT2",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 22, "GREQ_BLKW",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 23, "GREQ_BLKR",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 24, "TVC_PFH",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 25, "TVC_RESZ",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 26, "R_DMA1_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 27, "EIS",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 28, "ROT_DMA2_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 29, "ROT_DMA3_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 30, "ROT_DMA4_OUT3",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC }
};
struct smi_desc larb2_desc[] = {
	{ 0, "VENC_MC",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 1, "VENC_BSDMA",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 2, "VENC_MVQP",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 3, "VDEC_DMA",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 4, "VDNC_REC",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 5, "VDNC_POST0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 6, "VDNC_POST1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 7, "VDNC_ACP",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 8, "VENC_MC_ACP",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC }
};
struct smi_desc larb3_desc[] = {
	{ 0, "G2D_W",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 1, "G2D_R",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 2, "AUDIO_0",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 3, "AUDIO_1",	SMI_DEST_ALL, SMI_RW_ALL, SMI_BUS_GMC },
	{ 4, "GPU",	SMI_DEST_ALL, SMI_RW_RESPECTIVE, SMI_BUS_AXI }	//GPU: fake port#
};
struct smi_desc common_desc[] = {
	{ 0, "SMI_TOTAL",	SMI_DEST_NONE, SMI_RW_RESPECTIVE, SMI_BUS_NONE } //common: fake port#
};

#define SMI_LARB0_DESC_COUNT (sizeof(larb0_desc) / sizeof(struct smi_desc))
#define SMI_LARB1_DESC_COUNT (sizeof(larb1_desc) / sizeof(struct smi_desc))
#define SMI_LARB2_DESC_COUNT (sizeof(larb2_desc) / sizeof(struct smi_desc))
#define SMI_LARB3_DESC_COUNT (sizeof(larb3_desc) / sizeof(struct smi_desc))
#define SMI_COMMON_DESC_COUNT (sizeof(common_desc) / sizeof(struct smi_desc))
#define SMI_ALLPORT_COUNT (SMI_LARB0_DESC_COUNT+SMI_LARB1_DESC_COUNT+SMI_LARB2_DESC_COUNT+SMI_LARB3_DESC_COUNT+SMI_COMMON_DESC_COUNT)

#endif // _SMI_NAME_H_
