include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += leds_strobe.o

MTK_CUSTOM_PATH  := $(srctree)/drivers/misc/mediatek

subdir-ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/src/$(CONFIG_MTK_PLATFORM)/camera_hw
