#
# Makefile for nfc devices
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_LGE_NFC_PN547)	+= pn544_lge.o
#obj-$(CONFIG_LGE_NFC_PN547)	+= pn544_lge_hwadapter.o

ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
