include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y := board.o

# LGE_CHANGE_S
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_HIDDEN_RESET) += lge_hidden_reset.o

#obj-y += lge_handle_panic.o
#obj-y += lge_hidden_reset.o
