include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_MTK_VIDEOCODEC_DRIVER) += videocodec_kernel.o
obj-y += videocodec_kernel.o

obj-$(CONFIG_MTK_ACCDET) += $(subst ",,$(CONFIG_MTK_PLATFORM))/

