/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat May 10 18:56:22 2014
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI     GPIO_VIO28
#define GPIO_DVDD3_LCD     GPIO_VIO18
#define MSDC_POWER_MC1     MSDC_VMC


