/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat May 10 18:56:22 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_USB_ID_CHANNEL     0
#define AUXADC_PCB_REV_CHANNEL     1


#endif //_CUST_AUXADC_TOOL_H


